<?php
/**
 * WARNING: THE CODE IN THIS PROJECT IS REALLY SHIT, YOU'LL PROBABLY BE FIRED FROM YOUR JOB IF ANY ATTEMPT
 * IS MADE TRYING TO USE ANY PARTS OF THIS PROJECT.
 *
 * SO, YOU ARE WARNED
 */
require_once("index.html");

